menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/zp-j
    About: /about/
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
<<<<<<< HEAD
disqus: zhipeng
=======
disqus:
>>>>>>> upstream/master
duoshuo:

# Analytics
# google-analytics:
ga: UA-47515905-1

# Copyright Infomation
startyear: 2013

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
