menu:
    Archive: /archives/
    # GitHub: https://github.com/0x333333
    About: /about/
    Travel: https://blog.1pixel.cc
    Photography: https://1pixel.cc
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: zhipeng

# Analytics
# google-analytics:
ga: UA-47515905-1

# Copyright Infomation
startyear: 2013
