menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/zp-j
    About: /about/
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: zhipeng

# Analytics
# google-analytics:
ga: UA-47515905-1

# Copyright Infomation
startyear: 2013
